/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeBuyRouteImport } from './routes/what-we-buy'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'

const WhatWeBuyRoute = WhatWeBuyRouteImport.update({
  id: '/what-we-buy',
  path: '/what-we-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ServiceAreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/what-we-buy': typeof WhatWeBuyRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/what-we-buy': typeof WhatWeBuyRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas': typeof ServiceAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/what-we-buy': typeof WhatWeBuyRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/how-it-works'
    | '/service-areas'
    | '/what-we-buy'
    | '/service-areas/$city'
    | '/service-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/how-it-works'
    | '/what-we-buy'
    | '/service-areas/$city'
    | '/service-areas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/how-it-works'
    | '/service-areas'
    | '/what-we-buy'
    | '/service-areas/$city'
    | '/service-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  WhatWeBuyRoute: typeof WhatWeBuyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-buy': {
      id: '/what-we-buy'
      path: '/what-we-buy'
      fullPath: '/what-we-buy'
      preLoaderRoute: typeof WhatWeBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
  }
}

interface ServiceAreasRouteChildren {
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  WhatWeBuyRoute: WhatWeBuyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
