/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeBuyRouteImport } from './routes/what-we-buy'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'

const WhatWeBuyRoute = WhatWeBuyRouteImport.update({
  id: '/what-we-buy',
  path: '/what-we-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRoute
  '/what-we-buy': typeof WhatWeBuyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRoute
  '/what-we-buy': typeof WhatWeBuyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRoute
  '/what-we-buy': typeof WhatWeBuyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/how-it-works' | '/service-areas' | '/what-we-buy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/how-it-works' | '/service-areas' | '/what-we-buy'
  id: '__root__' | '/' | '/how-it-works' | '/service-areas' | '/what-we-buy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  WhatWeBuyRoute: typeof WhatWeBuyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-buy': {
      id: '/what-we-buy'
      path: '/what-we-buy'
      fullPath: '/what-we-buy'
      preLoaderRoute: typeof WhatWeBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  WhatWeBuyRoute: WhatWeBuyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
